dist: xenial
services:
  - xvfb

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

script: python -m pytest

notifications:
  email: true