language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

script: python -m pytest

notifications:
  email: false